name = "au-paradis-ofer"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-09-03"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BOOKINGS_KV"
id = "418006f70aab49e3a20ebc8b3d2ebd3f"